Vagrant.configure("2") do |config|

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
  config.vm.synced_folder "..", "/vln"

  config.vm.define "userone" do |userone|
    userone.vm.box = "ubuntu/focal64"
    userone.vm.hostname = "userone"
  end

  config.vm.define "usertwo" do |usertwo|
    usertwo.vm.box = "ubuntu/focal64"
    usertwo.vm.hostname = "usertwo"
  end

  config.vm.define "vlnserver" do |vlnserver|
    vlnserver.vm.box = "ubuntu/focal64"
    vlnserver.vm.hostname = "vlnserver"
    vlnserver.vm.network "private_network", ip: "192.168.33.17"
  end

end
